@startuml
!include Style.puml

actor User
participant ":Duke" as Duke
participant "<<class>>\nParser" as parser
participant "c:AddCommand" as add
participant "accounts:AccountList" as AL
participant "account:Account" as account
participant ":Ui" as ui

User -> Duke:run()
activate Duke

create parser
Duke -> parser: parseInput("add SGD 100")
activate parser

create add
parser -> add
activate add

add --> parser
deactivate add

parser --> Duke : c
deactivate parser

Duke -> add:execute(ui, accounts)
activate add
add -> add: processCommand()
activate add
add --> add
deactivate add

add -> AL : getAccount("SGD")
activate AL
AL --> add:account
deactivate

create account
add -> account: updateBalance("100","add")
activate account
account --> add
deactivate account
'to make destroy below activation bar
account -[hidden]->
destroy account

add -> add:printSuccess(ui)
activate add
add-> ui:printf(Message.SUCCESSFUL_ADD_COMMAND.getMessage(), "SGD", ""100")
activate ui
ui --> add
deactivate ui
add --> add
deactivate add
add --> Duke
deactivate add
add -[hidden]->
destroy add
Duke --> User
@enduml